<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_asset' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * lun. 09 janv. 2012 09:51:19 CET
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfAssetsLibraryPlugin.lib.model
 */
class sfAssetQuery extends BasesfAssetQuery
{

}
